services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

  nodeserver:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    image: pedrobraga/node:prod
    container_name: nodeserver
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: pedrobraga/nginx:prod
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"

networks: 
  nodenet:
    driver: bridge